### ISSUE TITLE
модульное тестирование 

### ISSUE THREAD

**Issue by Chectus** [trpo2023/cw-iv-222_todolist#2]
разработать идеи для тестирования функций кода

**Comment by Chectus** [comment]
проверить создание аккаунта на стороннем пк

**Comment by Chectus** [comment]
проверить использование разных символов при создании задачи

**Comment by Chectus** [comment]
> проверить использование разных символов при создании задачи

также попробовать использовать большое кол-во символов

**Comment by Chectus** [comment]
испытать удаление задач

**Comment by Chectus** [comment]
испытать выполнение задач
< испытание провалено, при попытке удаления задачи возникает ошибка
фиксим

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
make: *** [Makefile:61: run] Аварийный останов (сделан дамп памяти)

**Comment by Coder0302** [comment]
Complete add tests with great result!
